Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/conda/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/conda/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
daPlot, daPlotpd, legendList, gFig = ep.lmPlot(AFterm.where(AFterm.L<=2).sel(M=1),    # .sel(R=0).sel(Rp=0), #M=0 for R=Rp=0
                                               xDim = 't', pType = 'r', squeeze = False, cmap='vlag')  # Note squeeze = False required for 1D case (should add this to code!)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m/opt/conda/lib/python3.10/site-packages/pandas/core/indexes/base.py:3802[0m, in [0;36mIndex.get_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3801[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3802[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_engine[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mcasted_key[49m[43m)[49m
[1;32m   3803[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32m/opt/conda/lib/python3.10/site-packages/pandas/_libs/index.pyx:138[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32m/opt/conda/lib/python3.10/site-packages/pandas/_libs/index.pyx:165[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:2263[0m, in [0;36mpandas._libs.hashtable.Int64HashTable.get_item[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:2273[0m, in [0;36mpandas._libs.hashtable.Int64HashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 1

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[19], line 1[0m
[0;32m----> 1[0m daPlot, daPlotpd, legendList, gFig [38;5;241m=[39m ep[38;5;241m.[39mlmPlot([43mAFterm[49m[38;5;241;43m.[39;49m[43mwhere[49m[43m([49m[43mAFterm[49m[38;5;241;43m.[39;49m[43mL[49m[38;5;241;43m<[39;49m[38;5;241;43m=[39;49m[38;5;241;43m2[39;49m[43m)[49m[38;5;241;43m.[39;49m[43msel[49m[43m([49m[43mM[49m[38;5;241;43m=[39;49m[38;5;241;43m1[39;49m[43m)[49m,    [38;5;66;03m# .sel(R=0).sel(Rp=0), #M=0 for R=Rp=0[39;00m
[1;32m      2[0m                                                xDim [38;5;241m=[39m [38;5;124m'[39m[38;5;124mt[39m[38;5;124m'[39m, pType [38;5;241m=[39m [38;5;124m'[39m[38;5;124mr[39m[38;5;124m'[39m, squeeze [38;5;241m=[39m [38;5;28;01mFalse[39;00m, cmap[38;5;241m=[39m[38;5;124m'[39m[38;5;124mvlag[39m[38;5;124m'[39m)  [38;5;66;03m# Note squeeze = False required for 1D case (should add this to code!)[39;00m

File [0;32m/opt/conda/lib/python3.10/site-packages/xarray/core/dataarray.py:1329[0m, in [0;36mDataArray.sel[0;34m(self, indexers, method, tolerance, drop, **indexers_kwargs)[0m
[1;32m   1220[0m [38;5;28;01mdef[39;00m [38;5;21msel[39m(
[1;32m   1221[0m     [38;5;28mself[39m,
[1;32m   1222[0m     indexers: Mapping[Any, Any] [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[0;32m   (...)[0m
[1;32m   1226[0m     [38;5;241m*[39m[38;5;241m*[39mindexers_kwargs: Any,
[1;32m   1227[0m ) [38;5;241m-[39m[38;5;241m>[39m DataArray:
[1;32m   1228[0m [38;5;250m    [39m[38;5;124;03m"""Return a new DataArray whose data is given by selecting index[39;00m
[1;32m   1229[0m [38;5;124;03m    labels along the specified dimension(s).[39;00m
[1;32m   1230[0m 
[0;32m   (...)[0m
[1;32m   1327[0m [38;5;124;03m    Dimensions without coordinates: points[39;00m
[1;32m   1328[0m [38;5;124;03m    """[39;00m
[0;32m-> 1329[0m     ds [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_to_temp_dataset[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43msel[49m[43m([49m
[1;32m   1330[0m [43m        [49m[43mindexers[49m[38;5;241;43m=[39;49m[43mindexers[49m[43m,[49m
[1;32m   1331[0m [43m        [49m[43mdrop[49m[38;5;241;43m=[39;49m[43mdrop[49m[43m,[49m
[1;32m   1332[0m [43m        [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m
[1;32m   1333[0m [43m        [49m[43mtolerance[49m[38;5;241;43m=[39;49m[43mtolerance[49m[43m,[49m
[1;32m   1334[0m [43m        [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mindexers_kwargs[49m[43m,[49m
[1;32m   1335[0m [43m    [49m[43m)[49m
[1;32m   1336[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_from_temp_dataset(ds)

File [0;32m/opt/conda/lib/python3.10/site-packages/xarray/core/dataset.py:2501[0m, in [0;36mDataset.sel[0;34m(self, indexers, method, tolerance, drop, **indexers_kwargs)[0m
[1;32m   2440[0m [38;5;250m[39m[38;5;124;03m"""Returns a new dataset with each array indexed by tick labels[39;00m
[1;32m   2441[0m [38;5;124;03malong the specified dimension(s).[39;00m
[1;32m   2442[0m 
[0;32m   (...)[0m
[1;32m   2498[0m [38;5;124;03mDataArray.sel[39;00m
[1;32m   2499[0m [38;5;124;03m"""[39;00m
[1;32m   2500[0m indexers [38;5;241m=[39m either_dict_or_kwargs(indexers, indexers_kwargs, [38;5;124m"[39m[38;5;124msel[39m[38;5;124m"[39m)
[0;32m-> 2501[0m pos_indexers, new_indexes [38;5;241m=[39m [43mremap_label_indexers[49m[43m([49m
[1;32m   2502[0m [43m    [49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[43mindexers[49m[38;5;241;43m=[39;49m[43mindexers[49m[43m,[49m[43m [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43mtolerance[49m[38;5;241;43m=[39;49m[43mtolerance[49m
[1;32m   2503[0m [43m[49m[43m)[49m
[1;32m   2504[0m [38;5;66;03m# TODO: benbovy - flexible indexes: also use variables returned by Index.query[39;00m
[1;32m   2505[0m [38;5;66;03m# (temporary dirty fix).[39;00m
[1;32m   2506[0m new_indexes [38;5;241m=[39m {k: v[[38;5;241m0[39m] [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m new_indexes[38;5;241m.[39mitems()}

File [0;32m/opt/conda/lib/python3.10/site-packages/xarray/core/coordinates.py:421[0m, in [0;36mremap_label_indexers[0;34m(obj, indexers, method, tolerance, **indexers_kwargs)[0m
[1;32m    414[0m indexers [38;5;241m=[39m either_dict_or_kwargs(indexers, indexers_kwargs, [38;5;124m"[39m[38;5;124mremap_label_indexers[39m[38;5;124m"[39m)
[1;32m    416[0m v_indexers [38;5;241m=[39m {
[1;32m    417[0m     k: v[38;5;241m.[39mvariable[38;5;241m.[39mdata [38;5;28;01mif[39;00m [38;5;28misinstance[39m(v, DataArray) [38;5;28;01melse[39;00m v
[1;32m    418[0m     [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m indexers[38;5;241m.[39mitems()
[1;32m    419[0m }
[0;32m--> 421[0m pos_indexers, new_indexes [38;5;241m=[39m [43mindexing[49m[38;5;241;43m.[39;49m[43mremap_label_indexers[49m[43m([49m
[1;32m    422[0m [43m    [49m[43mobj[49m[43m,[49m[43m [49m[43mv_indexers[49m[43m,[49m[43m [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43mtolerance[49m[38;5;241;43m=[39;49m[43mtolerance[49m
[1;32m    423[0m [43m[49m[43m)[49m
[1;32m    424[0m [38;5;66;03m# attach indexer's coordinate to pos_indexers[39;00m
[1;32m    425[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m indexers[38;5;241m.[39mitems():

File [0;32m/opt/conda/lib/python3.10/site-packages/xarray/core/indexing.py:121[0m, in [0;36mremap_label_indexers[0;34m(data_obj, indexers, method, tolerance)[0m
[1;32m    119[0m [38;5;28;01mfor[39;00m dim, index [38;5;129;01min[39;00m indexes[38;5;241m.[39mitems():
[1;32m    120[0m     labels [38;5;241m=[39m grouped_indexers[dim]
[0;32m--> 121[0m     idxr, new_idx [38;5;241m=[39m [43mindex[49m[38;5;241;43m.[39;49m[43mquery[49m[43m([49m[43mlabels[49m[43m,[49m[43m [49m[43mmethod[49m[38;5;241;43m=[39;49m[43mmethod[49m[43m,[49m[43m [49m[43mtolerance[49m[38;5;241;43m=[39;49m[43mtolerance[49m[43m)[49m
[1;32m    122[0m     pos_indexers[dim] [38;5;241m=[39m idxr
[1;32m    123[0m     [38;5;28;01mif[39;00m new_idx [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m:

File [0;32m/opt/conda/lib/python3.10/site-packages/xarray/core/indexes.py:241[0m, in [0;36mPandasIndex.query[0;34m(self, labels, method, tolerance)[0m
[1;32m    237[0m                 [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(
[1;32m    238[0m                     [38;5;124mf[39m[38;5;124m"[39m[38;5;124mnot all values found in index [39m[38;5;132;01m{[39;00mcoord_name[38;5;132;01m!r}[39;00m[38;5;124m"[39m
[1;32m    239[0m                 )
[1;32m    240[0m         [38;5;28;01melse[39;00m:
[0;32m--> 241[0m             indexer [38;5;241m=[39m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mindex[49m[38;5;241;43m.[39;49m[43mget_loc[49m[43m([49m[43mlabel_value[49m[43m)[49m
[1;32m    242[0m [38;5;28;01melif[39;00m label[38;5;241m.[39mdtype[38;5;241m.[39mkind [38;5;241m==[39m [38;5;124m"[39m[38;5;124mb[39m[38;5;124m"[39m:
[1;32m    243[0m     indexer [38;5;241m=[39m label

File [0;32m/opt/conda/lib/python3.10/site-packages/pandas/core/indexes/base.py:3804[0m, in [0;36mIndex.get_loc[0;34m(self, key, method, tolerance)[0m
[1;32m   3802[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_engine[38;5;241m.[39mget_loc(casted_key)
[1;32m   3803[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:
[0;32m-> 3804[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m [38;5;21;01merr[39;00m
[1;32m   3805[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3806[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3807[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3808[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3809[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 1

