Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/conda/lib/python3.9/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/opt/conda/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 558, in async_execute
    await self.async_execute_cell(
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/conda/lib/python3.9/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Plot some distributions from specified BLMs

# Set specific LM coeffs by list with setBLMs, items are [l,m,value]
from epsproc.sphCalc import setBLMs

# BLM = setBLMs([[0,0,1],[1,1,1],[2,2,1]])
# BLM = setBLMs([[0,0,1,1,1],[1,1,1,0.5,0.2],[2,2,1,1,0.2]])   # Note different index
BLM = setBLMs([[0,0,1,1,1,1],[1,1,0,0.5,0.8,1],[2,0,1,0.5,0,0],
               [4,2,0,0,0,0.5],[4,-2,0,0,0,0.5]])

# Set the backend to 'pl' for an interactive surface plot with Plotly
# NOTE PL FIG RETURN BROKEN FOR THIS CASE (ePSproc v1.3.1), so run sphSumPlotX too.
dataPlot, figObj = ep.sphFromBLMPlot(BLM, facetDim='t', plotFlag = False, backend = plotBackend);
figObj = ep.sphSumPlotX(dataPlot,facetDim='t', plotFlag = False, backend = plotBackend);

# And GLUE for display later with caption
# from myst_nb import glue
# glue("padExamplePlot", figObj[0], display=False);
# Glue with Plotly wrapper.
# gluePlotly("padExamplePlot", figObj[0])   # Working in Render test notebook, but not here? Issue with subplots?

# Test in separate cell...
gluePlotly("padExamplePlot", figObj[0])   # Working in Render test notebook, but not here? Issue with subplots?
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mValueError[0m                                Traceback (most recent call last)
[0;32m/tmp/ipykernel_50215/3449156612.py[0m in [0;36m<module>[0;34m[0m
[1;32m     21[0m [0;34m[0m[0m
[1;32m     22[0m [0;31m# Test in separate cell...[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 23[0;31m [0mgluePlotly[0m[0;34m([0m[0;34m"padExamplePlot"[0m[0;34m,[0m [0mfigObj[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m   [0;31m# Working in Render test notebook, but not here? Issue with subplots?[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/jake-home/buildTmp/_latest_build/html/doc-source/scripts/setup_notebook.py[0m in [0;36mglueWrapper[0;34m(name, fig, **kwargs)[0m
[1;32m    128[0m                 [0;31m# Without Panel some basic plot types work, but not surface plots - may also be browser-dependent?[0m[0;34m[0m[0;34m[0m[0m
[1;32m    129[0m                 [0;31m# Or due to maths bug, per https://jupyterbook.org/en/stable/interactive/interactive.html#plotly[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 130[0;31m                 [0;32mreturn[0m [0mglue[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mpn[0m[0;34m.[0m[0mpane[0m[0;34m.[0m[0mPlotly[0m[0;34m([0m[0mfig[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m,[0m [0mdisplay[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    131[0m [0;34m[0m[0m
[1;32m    132[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/jake-home/buildTmp/_latest_build/html/doc-source/scripts/setup_notebook.py[0m in [0;36mglueWrapper[0;34m(name, fig, **kwargs)[0m
[1;32m    128[0m                 [0;31m# Without Panel some basic plot types work, but not surface plots - may also be browser-dependent?[0m[0;34m[0m[0;34m[0m[0m
[1;32m    129[0m                 [0;31m# Or due to maths bug, per https://jupyterbook.org/en/stable/interactive/interactive.html#plotly[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 130[0;31m                 [0;32mreturn[0m [0mglue[0m[0;34m([0m[0mname[0m[0;34m,[0m [0mpn[0m[0;34m.[0m[0mpane[0m[0;34m.[0m[0mPlotly[0m[0;34m([0m[0mfig[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m,[0m [0mdisplay[0m[0;34m=[0m[0;32mFalse[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    131[0m [0;34m[0m[0m
[1;32m    132[0m             [0;32melse[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/conda/lib/python3.9/site-packages/panel/pane/plotly.py[0m in [0;36m__init__[0;34m(self, object, **params)[0m
[1;32m     95[0m [0;34m[0m[0m
[1;32m     96[0m     [0;32mdef[0m [0m__init__[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mobject[0m[0;34m=[0m[0;32mNone[0m[0;34m,[0m [0;34m**[0m[0mparams[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 97[0;31m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mobject[0m[0;34m,[0m [0;34m**[0m[0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     98[0m         [0mself[0m[0;34m.[0m[0m_figure[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m
[1;32m     99[0m         [0mself[0m[0;34m.[0m[0m_event[0m [0;34m=[0m [0;32mNone[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/conda/lib/python3.9/site-packages/panel/pane/base.py[0m in [0;36m__init__[0;34m(self, object, **params)[0m
[1;32m    140[0m         [0mapplies[0m [0;34m=[0m [0mself[0m[0;34m.[0m[0mapplies[0m[0;34m([0m[0mobject[0m[0;34m,[0m [0;34m**[0m[0;34m([0m[0mparams[0m [0;32mif[0m [0mself[0m[0;34m.[0m[0m_applies_kw[0m [0;32melse[0m [0;34m{[0m[0;34m}[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    141[0m         [0;32mif[0m [0;34m([0m[0misinstance[0m[0;34m([0m[0mapplies[0m[0;34m,[0m [0mbool[0m[0;34m)[0m [0;32mand[0m [0;32mnot[0m [0mapplies[0m[0;34m)[0m [0;32mand[0m [0mobject[0m [0;32mis[0m [0;32mnot[0m [0;32mNone[0m [0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 142[0;31m             [0mself[0m[0;34m.[0m[0m_type_error[0m[0;34m([0m[0mobject[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    143[0m [0;34m[0m[0m
[1;32m    144[0m         [0msuper[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0m__init__[0m[0;34m([0m[0mobject[0m[0;34m=[0m[0mobject[0m[0;34m,[0m [0;34m**[0m[0mparams[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/conda/lib/python3.9/site-packages/panel/pane/base.py[0m in [0;36m_type_error[0;34m(self, object)[0m
[1;32m    158[0m [0;34m[0m[0m
[1;32m    159[0m     [0;32mdef[0m [0m_type_error[0m[0;34m([0m[0mself[0m[0;34m,[0m [0mobject[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 160[0;31m         raise ValueError("%s pane does not support objects of type '%s'." %
[0m[1;32m    161[0m                          (type(self).__name__, type(object).__name__))
[1;32m    162[0m [0;34m[0m[0m

[0;31mValueError[0m: Plotly pane does not support objects of type 'Plotly'.
ValueError: Plotly pane does not support objects of type 'Plotly'.

